#:schema https://json.schemastore.org/pyproject.json

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[dependency-groups]
lint = ["ruff>=0.9.2"]
types = ["types-jsonschema>=4.23.0.20241208", "pyright>=1.1.392.post0"]

[project]
name = "simple-resume"
version = "1.0.0"
description = "CLI tool to build a resume using a JSON Resume file"
authors = [{ name = "Sebastián Altamirano" }]
dependencies = [
	"Babel>=2.16.0",
	"Flask>=3.1.0",
	"jinjax[whitenoise]>=0.48",
	"jsonschema>=4.23.0",
	"livereload>=2.7.1",
	"playwright>=1.49.1",
	"typer>=0.15.1",
]
requires-python = "==3.12.*"
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
simple-resume = "simple_resume.__main__:app"

[tool.pdm]
distribution = true

[tool.pdm.scripts]
extract-messages = "pybabel extract . -F simple_resume/translations/babel.cfg -o simple_resume/translations/messages.pot"
initialize-messages = "pybabel init -i simple_resume/translations/messages.pot -d simple_resume/translations -l"
update-messages = "pybabel update -i simple_resume/translations/messages.pot -d simple_resume/translations"
compile-messages = "pybabel compile -d simple_resume/translations"
format.composite = [
	"ruff check --select I --fix",             # Sort imports
	"ruff format",
	"npx prettier --write --ignore-unknown .",
]
lint.composite = ["ruff check", "pyright"]
lint.env.PYRIGHT_PYTHON_PYLANCE_VERSION = "latest-release"
# Hooks
post_install = "./scripts/run_frontman.sh install"
pre_build = { composite = ["compile-messages"] }

[tool.pyright]
include = ["simple_resume"]
typeCheckingMode = "strict"

[tool.ruff]
indent-width = 4
line-length = 100
src = ["simple_resume"]

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
ignore = ["ANN101", "D107", "ISC001"]
select = [
	"A",
	"ANN",
	"ARG",
	"ASYNC",
	"B",
	"BLE",
	"C4",
	"C90",
	"D",
	"DTZ",
	"E",
	"EM",
	"ERA",
	"F",
	"FA",
	"FBT",
	"FIX",
	"FURB",
	"I",
	"ICN",
	"INP",
	"INT",
	"ISC",
	"N",
	"PERF",
	"PIE",
	"PLC",
	"PLE",
	"PLR",
	"PLW",
	"PTH",
	"Q",
	"RET",
	"RUF",
	"SIM",
	"SLF",
	"SLOT",
	"T10",
	"T20",
	"TCH",
	"TID",
	"TRY",
	"UP",
	"W",
	"YTT",
]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.pydocstyle]
convention = "google"
