#:schema https://json.schemastore.org/pyproject.json

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
	"hatchling>=1.27.0",
	"poethepoet>=0.32.2",
	"pyinstaller>=6.12.0",
	"pyinstaller-versionfile>=3.0.0",
	"pyright>=1.1.394",
	"ruff>=0.9.6",
	"types-portpicker>=1.6.0.0",
	"types-requests>=2.32.0.20241016",
]

[project]
dependencies = [
	"Babel>=2.17.0",
	"Flask>=3.1.0",
	"email-validator>=2.2.0",
	"jinjax[whitenoise]>=0.48",
	"livereload>=2.7.1",
	"playwright>=1.50.0",
	"portpicker>=1.6.0",
	"pydantic>=2.10.6",
	"pydantic-extra-types[phonenumbers,pycountry,semver]>=2.10.2",
	"requests>=2.32.3",
	"tldextract>=5.1.3",
	"typer>=0.15.1",
]
requires-python = ">=3.12"
name = "simple-resume"
version = "1.0.0"
description = "CLI tool to build a resume using a JSON Resume file"
authors = [{ name = "Sebastián Altamirano" }]
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
simple-resume = "simple_resume.__main__:app"

[tool.hatch.build.hooks.custom]
dependencies = ["Babel", "poethepoet"]

[tool.hatch.build.targets.sdist]
include = [
	".python-version",
	"app.spec",
	"docs",
	"frontman.json",
	"scripts/run_frontman.sh",
	"simple_resume",
	"uv.lock",
]

[tool.hatch.build.targets.wheel]
artifacts = ["simple_resume/static", "simple_resume/translations/**/LC_MESSAGES/messages.mo"]
exclude = [
	"simple_resume/translations/**/LC_MESSAGES/messages.po",
	"simple_resume/translations/babel.cfg",
]
include = ["simple_resume"]

[tool.poe.tasks]
# Build (standalone)
build-standalone.cmd = "pyinstaller app.spec --noconfirm"
build-standalone.deps = ["compile-messages", "download-assets"]

# Format
_format-prettier = "npx prettier --write --ignore-unknown ."
_format-ruff = "ruff format"
_sort-imports = "ruff check --select I --fix"
format = ["_format-prettier", "_format-ruff", "_sort-imports"]

# Lint
_lint-pyright = { cmd = "pyright", env = { PYRIGHT_PYTHON_PYLANCE_VERSION = "latest-release" } }
_lint-ruff = "ruff check"
lint = ["_lint-ruff", "_lint-pyright"]

# Translation management
_extract-messages = """pybabel extract simple_resume
	--add-location file
	--mapping-file simple_resume/translations/babel.cfg
	--omit-header
	--output-file simple_resume/translations/messages.pot
	--sort-output
	--width 100
"""

_update-messages = """pybabel update
	--ignore-obsolete
	--input-file simple_resume/translations/messages.pot
	--omit-header
	--output-dir simple_resume/translations
	--width 100
"""

# `--use-fuzzy` is necessary because `.po` files without headers are marked as fuzzy.
# https://github.com/python-babel/babel/issues/688
compile-messages = "pybabel compile --directory simple_resume/translations --use-fuzzy"

initialize-messages.sequence = [
	"_extract-messages",
	# `--init-missing` fails if the directory does not exist.
	# https://github.com/python-babel/babel/issues/1139
	{ cmd = "mkdir -p simple_resume/translations/${locale}/LC_MESSAGES" },
	"_update-messages --init-missing --locale ${locale}",
]
initialize-messages.args = [
	{ name = "locale", positional = true, required = true, type = "string" },
]

update-messages = ["_extract-messages", "_update-messages"]

# Template dependency management
download-assets = "scripts/run_frontman.sh install"

[tool.pyright]
include = ["simple_resume"]
pythonPlatform = "All"
typeCheckingMode = "strict"

[tool.ruff]
indent-width = 4
line-length = 100
src = ["simple_resume"]

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
ignore = ["D107", "ISC001"]
select = [
	"A",
	"ANN",
	"ARG",
	"ASYNC",
	"B",
	"BLE",
	"C4",
	"C90",
	"D",
	"DTZ",
	"E",
	"EM",
	"ERA",
	"F",
	"FA",
	"FBT",
	"FIX",
	"FURB",
	"I",
	"ICN",
	"INP",
	"INT",
	"ISC",
	"N",
	"PERF",
	"PIE",
	"PLC",
	"PLE",
	"PLR",
	"PLW",
	"PTH",
	"Q",
	"RET",
	"RUF",
	"SIM",
	"SLF",
	"SLOT",
	"T10",
	"T20",
	"TID",
	"TRY",
	"UP",
	"W",
	"YTT",
]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.uv]
required-environments = ["sys_platform == 'linux'", "sys_platform == 'win32'"]
